env: "local"  #local/prod
storage_path: "./src/storage/storage.db"
http_server:
    address: "localhost:8082"
    timeout: 4s # time for reading request and answering, but not processing
    idle_timeout: 60s # constant connection for multiple requests for a short time